// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StudioCRM.Infrastructure.Persistence;

#nullable disable

namespace StudioCRM.Infrastructure.Migrations
{
    [DbContext(typeof(StudioCRMDbContext))]
    [Migration("20260517103000_RemoveClientProgressPercent")]
    partial class RemoveClientProgressPercent
    {
    }
}
